services:
  - type: web
    name: poligram-website
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn poligram_website.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "poligram-website.onrender.com,*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: poligram-db
          property: connectionString
    plan: starter
    region: frankfurt

databases:
  - name: poligram-db
    databaseName: poligram
    user: poligram_user
    plan: starter

